### ISSUE TITLE
How to do the uninstall  of golang ?

### ISSUE THREAD

**Issue by tjyang** [jackscott/golang-formula#1]
I was able to run following command to install golang 1.6 version on CentOS 7.

salt-call state.sls golang test=false

The question is how to tackle the reverse of  "install" action cleanly ?

**Comment by jackscott** [comment]
@tjyang Thanks for checking out this formula!

While there isn't a state to do this explicitly, you can remove things manually by unlinking the pointers [here](https://github.com/jackscott/golang-formula/blob/9b5eb89eb68224e32e648fb980f088caf0080b15/golang/init.sls#L70-L80) and [here](https://github.com/jackscott/golang-formula/blob/9b5eb89eb68224e32e648fb980f088caf0080b15/golang/init.sls#L58-L66) and then  remove the directory at `/usr/local/golang` (unless you changed `prefix`) and finally `/etc/profile.d/golang.sh`

Hope that helps...

**Comment by tjyang** [comment]
Thanks for the pointer on removal of golang installation. I might take up the task of creating an uninstall state. This uninstall state will enable the golang version upgrade process. (ie, remove existing install and install the newer version).
